version: "3"
services:
  flyway:
    image: flyway/flyway
    command: -locations=filesystem:/flyway/sql -url=jdbc:postgresql://192.168.99.100:5432/postgres -schemas=public -user=postgres -password=postgres -connectRetries=60 -baselineOnMigrate=true migrate
    volumes:
       - .:/flyway/sql

